webtalk_init -webtalk_dir C:\\Users\\DOUYOUZHE\\Desktop\\4444422222111118888\\AAAEEESSS\\AAAEEESSS.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 9 02:51:23 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174413354_207303390_210602269_547" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "s7ut59a0d5m0g2epif25j6mo0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_28" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1447007766069" -context "sdk\\\\hardware/1447007766069"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1447007766069"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1447007766069"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.2" -context "sdk\\\\hardware/1447007766069"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1447007766069"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1447007766069"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1447007766069"
webtalk_transmit -clientid 2020251208 -regid "174413354_207303390_210602269_547" -xml C:\\Users\\DOUYOUZHE\\Desktop\\4444422222111118888\\AAAEEESSS\\AAAEEESSS.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\DOUYOUZHE\\Desktop\\4444422222111118888\\AAAEEESSS\\AAAEEESSS.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\DOUYOUZHE\\Desktop\\4444422222111118888\\AAAEEESSS\\AAAEEESSS.sdk\\webtalk\\sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
