# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths {
  C:/Users/DOUYOUZHE/Desktop/AES256Version/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  C:/users/douyouzhe/desktop/4444422222111118888/ip_repo/myip_1.0
  c:/users/douyouzhe/desktop/aes256version/ip_repo/myip_1.0
} [current_fileset]

add_files C:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_axi_tft_0_0/design_1_axi_tft_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_axi_tft_0_0/design_1_axi_tft_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_axi_tft_0_0/design_1_axi_tft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_s01_mmu_0/design_1_s01_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_s02_mmu_0/design_1_s02_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib C:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
read_xdc C:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/constrs_1/imports/4444422222111118888/zedboard_vga.xdc
set_property used_in_implementation false [get_files C:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.srcs/constrs_1/imports/4444422222111118888/zedboard_vga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS/AAAEEESSS.cache/wt [current_project]
set_property parent.project_dir C:/Users/DOUYOUZHE/Desktop/AES256Version/AAAEEESSS [current_project]
catch { write_hwdef -file design_1_wrapper.hwdef }
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint design_1_wrapper.dcp
report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb
